Add method for obtaining the raw TCP socket file descriptor
mullvad/udp-over-tcp pull request #33
Opened 2022-11-21 16:25 UTC by dlon

Useful to have since we want to exclude the socket on Android.

2022-11-21 16:30 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/33)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dlon and @faern)

___
*[`src/udp2tcp.rs` line 191 at r1](https://reviewable.io/reviews/mullvad/udp-over-tcp/33#-NHQ0QVG3StgYVegvavh:-NHQ0QVG3StgYVegvavi:b2b7o9s) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/faa1bec6d73c6fc60416aaf398770635cece0fdd/src/udp2tcp.rs#L191)):*
> ```XML
>     }
> 
>     async fn connect(mut self) -> Result<TcpForwardSocket, ConnectError> {
> ```

Couldn't this, instead of returning `Self` return `TcpStream` instead? It would eliminate the need for panicking, would it not?


<!-- Sent from Reviewable.io -->

2022-11-21 17:18 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/33)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @faern and @pinkisemils)

___
*[`src/udp2tcp.rs` line 191 at r1](https://reviewable.io/reviews/mullvad/udp-over-tcp/33#-NHQ0QVG3StgYVegvavh:-NHQBWk4E90r1oeigTO8:b-896fix) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/faa1bec6d73c6fc60416aaf398770635cece0fdd/src/udp2tcp.rs#L191)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Couldn't this, instead of returning `Self` return `TcpStream` instead? It would eliminate the need for panicking, would it not?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-22 17:01 UTC, pinkisemils approved these changes
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/33)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faern)



<!-- Sent from Reviewable.io -->

2022-11-23 09:27 UTC, pinkisemils approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/33)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faern)



<!-- Sent from Reviewable.io -->

2022-11-23 13:57 UTC, merged